# Generated by Django 5.2.4 on 2025-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(verbose_name='RT543060')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField()),
            ],
        ),
    ]
